import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import Header from "@/components/layout/header";
import { ThemeProvider } from "../components/theme/theme-provider";
import { Separator } from "@/components/ui/separator";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "TalentLink - Помощник для соискателя и рекрутера",
    template: "%s | TalentLink",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <Separator />
          {/* <main className={inter.className}>{children}</main> */}
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
